[workspace]
members = [
    "air-script",
    "parser",
    "pass",
    "mir",
    "air",
    "codegen/masm",
    "codegen/winterfell",
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.78"
